drop table Niveluri;
drop table Rezervare;
drop table Camere;
drop table Continut_Minibar;
drop table Angajati;
drop sequence id_camera_seq;
drop sequence id_rezervare_seq;
drop sequence id_minibar_seq;
drop sequence id_angajat_seq;